ALTER TABLE candidates ADD COLUMN IF NOT EXISTS rua TEXT;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS porta TEXT;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS codigo_postal TEXT;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS cidade TEXT;
